default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "Josiah") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: ticket_sales_problem_development

test:
  <<: *default
  database: ticket_sales_problem_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "ticket_sales_problem_production") %>
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
    host: <%= ENV["PGHOST"] %>
    port: <%= ENV["PGPORT"] %>
  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "ticket_sales_problem_production_queue") %>
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
    host: <%= ENV["PGHOST"] %>
    migrations_paths: db/queue_migrate